//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class ImageTableNext
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DisplayName("UploadFile")]
        public string ImagePath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public int Price { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public Nullable<int> ImageId { get; set; }
        public string Brand { get; set; }
        public string Material_Type { get; set; }
        public string Manufacturer { get; set; }
        public string Country_of_Origin { get; set; }
        public string Item_Weight { get; set; }
        public string Item_Dimensions_LxWxH { get; set; }
        public string Sport { get; set; }

    }


}
