//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public Nullable<int> Price { get; set; }
        public string Color { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Brand { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> DateandTime { get; set; }
    }
}
